feat(route): added AppRouter to manage routes
PyNorte/pynorte2023-site pull request #15
Opened 2023-04-25 16:26 UTC by ramontrovao

# Descrição

Inclua um resumo das alterações e qual problema foi corrigido. Inclua também motivação e/ou contextos relevantes. Liste todas as dependências necessárias para essa alteração.

Fixes # (issue)

## Tipo de mudança 🏗️

_Exclua as opções que não são relevantes._

Minha mudança é uma:

- [ ] Correção de bug (alteração que corrige um problema)
- [X ] Novo recurso (alteração que adiciona funcionalidades)
- [ ] Esta alteração requer uma atualização de documentação

## Como isso foi testado? 🧪

Adicionei o componente "Landing" como pasta na rota raiz "/" e tudo deu certo como o esperado. Ainda falta

## Checklist da PR ✅

- [ X] Meu código segue as diretrizes de estilo deste projeto
- [ X] Realizei uma autoavaliação do meu próprio código
- [ X] Fiz alterações correspondentes na documentação
- [X ] Minhas alterações não geram novos `warnings`
- [ X] O título do meu PR está seguindo o padrão <type>(scope): subject.
  - Exemplo 1 (com escopo): feat(page): add collaborators page
  - Exemplo 2 (sem escopo): fix: prevent auto reload

2023-04-25 16:47 UTC, Azanniel requested changes

2023-04-25 16:47 UTC, Azanniel commented on src/router.tsx
> +  )
Um bom pattern que você poderia usar quanto a nomenclatura seria nomear o arquivo como `Router.tsx` usando maiúsculo, pois refere-se a um componente React. Sendo assim ele exportaria um component `export function Router(){....`

Mas caso queira deixar como `AppRouter` poderia renomar o arquivo para `AppRouter.tsx`

2023-04-25 16:47 UTC, Azanniel commented on src/App.tsx
Caso o outro comentário seja resolvido essa importação irá mudar ou para `import { Router } from './Router'` ou para `import { AppRouter } from './AppRouter'`

2023-04-25 16:56 UTC, Azanniel commented on src/router.tsx
>        <Route Component={Landing} path="/pynorte2023-site" />
A questão da URL base é uma coisa um pouco complicada por conta do github-pages. 

Dei uma olhada em algumas documentações que diziam que temos que adicionar o nome do repo dentro das configurações do vite na propriedade `base`, mas acredito que isso dificulta um pouco a questão da url base com react-router-dom.

Caso tenha alguma solução essa discussão está aberta.

2023-04-28 01:11 UTC, ramontrovao commented on src/App.tsx
Resolvido. Alterei o nome do componente para Router e o nome do arquivo também.

`import { Router } from './Router'`

2023-04-28 01:11 UTC, ramontrovao commented on src/router.tsx
> +  )
Realizei essa alteração. O nome do arquivo de gerenciamento de rotas ficou como `Router.tsx`.

2023-04-28 14:17 UTC, Azanniel commented on src/router.tsx
>        <Route Component={Landing} path="/pynorte2023-site" />
Isso será resolvido com as configurações de domínio da issue https://github.com/PyNorte/pynorte2023-org/issues/27

2023-04-28 14:48 UTC, Azanniel requested changes

2023-04-28 14:48 UTC, Azanniel commented on package.json
> +  "homepage": "https://pynorte.github.io/pynorte2023-site",
Acredito que não seja necessário adicionar a homepage nesse momento enquanto não temos domínio.

2023-04-28 14:48 UTC, Azanniel commented on src/components/AnchorCustom.tsx
Acredito que isso se encaixa no problema de componentização prematura. 

O link pode muito bem ser usado em diferentes momentos no `html` somente com:

```tsx
<a className="text-xl text-white hover:text-green-500 transition-all duration-150">
  <BsInstagram />
</a>
```

acredito que isso seja melhor do que realizar um componentização prematura e tornar a estrutura um pouco mais complexa.

2023-04-28 14:48 UTC, Azanniel commented on src/layouts/DefaultLayout.tsx
> +      {/* Header here */}
Remover o comentário 😉

2023-04-28 14:48 UTC, Azanniel commented on src/pages/Landing.tsx
Não é necessário estar no commit, pois não houve nenhuma mudança relevante.

Quanto ao conteúdo já existente no arquivo antes do commit, pode deixar.

2023-04-28 14:48 UTC, Azanniel commented on src/pages/NotFound.tsx
> +      <img className="w-full md:w-[20rem]" src={logo} alt="" />
```suggestion
      <img className="w-full md:w-80" src={logo} alt="" />
```

2023-04-28 14:48 UTC, Azanniel commented on src/pages/NotFound.tsx
> +      </span>
```suggestion
      <span className="text-white text-center text-sm md:text-lg mt-5">
        O conteúdo que você tentou acessar não foi encontrado
      </span>
```

2023-04-28 14:48 UTC, Azanniel commented on src/router.tsx
> +        <Route Component={NotFound} path="*" />
O componente `NotFound` não precisa estar no layout a não ser que o time de design confirme isso com um protótipo.

2023-04-28 14:48 UTC, Azanniel commented on src/router.tsx
> +        <Route Component={NotFound} path="*" />
Seria interessante usar como na [documentação](https://reactrouter.com/en/main/components/routes).
Veja esse trecho tirado de lá:

```tsx
<Routes>
  <Route path="/" element={<Dashboard />}>
    <Route
      path="messages"
      element={<DashboardMessages />}
    />
    <Route path="tasks" element={<DashboardTasks />} />
  </Route>
  <Route path="about" element={<AboutPage />} />
</Routes>
```

2023-04-28 14:48 UTC, Azanniel commented on tailwind.config.js
> +        footer_background: '#282828',
Você pode substituir o zinc-800 ao invês de criar uma específica para o footer, pois são bem parecidas.

![image](https://user-images.githubusercontent.com/71537090/235178990-ffaa2bc4-e68f-4849-9052-ce7437569353.png)

2023-04-28 14:48 UTC, Azanniel commented on vite.config.ts
> +  base: '/pynorte2023-site',
Talvez isso possa quebrar no github-pages. Ele precisa que seja `/REPO/`

Veja a documentação: https://vitejs.dev/guide/static-deploy.html#gitlab-pages-and-gitlab-ci

2023-04-30 00:21 UTC, merged